name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  envied: ^1.1.1
  equatable: ^2.0.7
  firebase_analytics: ^11.5.2
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.1.1
  internet_connection_checker_plus: ^2.7.2
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  path_provider: ^2.1.5
  retrofit: ^4.4.2
  talker: ^4.9.2
  talker_bloc_logger: ^4.9.2
  talker_dio_logger: ^4.9.2

dev_dependencies:
  build_runner: ^2.5.4
  drift_dev: ^2.27.0
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  retrofit_generator: ^9.2.0
  test: ^1.25.15

flutter:
  generate: true
  uses-material-design: true