name: Test & Build

on:
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "18.x"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.29.2'

    - name: Get FLutter packages
      run: flutter pub get

    - name: Check for lints
      run: flutter analyze

    - name: Run all tests
      run: flutter test

    - name: Flutter build apk
      run: flutter build apk --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: app-release.apk

    - uses: nickwph/firebase-app-distribution-action@v1
      with:
        file: build/app/outputs/flutter-apk/app-release.apk
        app: ${{ secrets.FIREBASE_APP_ID }}
        credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
        release-notes: "Release notes..."
        groups: "testers"
