name: Test & Build

on:
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop

jobs:
  Test-and-distribute:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "18.x"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.29.2'

    - name: Get FLutter packages
      run: flutter pub get

    - name: Create env.dart
      run: |
        mkdir -p lib/env
        echo "class Env {" > lib/env/env.dart
        echo "  static const String firebaseOptionsApiKey = '${{ secrets.FIREBASE_OPTIONS_API_KEY }}';" >> lib/env/env.dart
        echo "  static const String firebaseApiKey = '${{ secrets.FIREBASE_FIRESTORE_API_KEY }}'" >> lib/env/env.dart
        echo "}" >> lib/env/env.dart

    - name: Check for lints
      run: flutter analyze

    - name: Run all tests
      run: flutter test

    - name: Flutter build apk
      run: flutter build apk --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release.apk

    - uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
        groups: testers
        file: app-release.apk
